# Dataset 5 — Wind & Solar Energy Production (Kaggle)
**Situação**  
Um operador de um portfólio de fontes renováveis deseja comparar a ocorrência de períodos de alta produção solar e alta produção eólica. Como as duas fontes possuem escalas próprias, cada uma deverá ser comparada com o seu próprio valor máximo.

---

Grupo:
| Nome | RM |
| --- | --- |
| Caio Marinho Pereira | 572873|
<br>

## Workflow Orange
Workflow realizado no Orange para mineração de dados. Não foram encontrados valores ausentes. Foi gerado uma amostra de 20% dos dados.  
![untitled2.svg]()

## Import de Bibliotecas
Adiciona as bibliotecas de análise de dados que serão usadas.

In [1]:
import pandas as pd

## Carregar dados externos
Carrega a planilha com os dados, já tratados, e traduz o nome das colunas para o português.

In [14]:
dados = pd.read_csv('/content/solar-wind.csv')

solar = dados[dados["Source"] == "Solar"].copy()
eolica = dados[dados["Source"] == "Wind"].copy()

In [19]:
solar = solar.rename(columns = {'Date': 'Data',
                                'Start_Hour': 'Horario_inicial',
                                'End_Hour': 'Horario_final',
                                'Source': 'Fonte',
                                'Day-of_Year': 'Dia_do_ano',
                                'Day_Name': 'Dia_nome',
                                'Month_Name': 'Mes_nome',
                                'Season': 'Estacao',
                                'Production': 'Producao'})

eolica = eolica.rename(columns = {'Date': 'Data',
                                'Start_Hour': 'Horario_inicial',
                                'End_Hour': 'Horario_final',
                                'Source': 'Fonte',
                                'Day-of_Year': 'Dia_do_ano',
                                'Day_Name': 'Dia_nome',
                                'Month_Name': 'Mes_nome',
                                'Season': 'Estacao',
                                'Production': 'Producao'})

## Maiores valores de Produção

### Solar

In [22]:
maior_sol = solar['Producao'].max()
print(f"Maior valor de Produção Solar registrada: {maior_sol:.3f} MWh")

Maior valor de Produção Solar registrada: 16316.000 MWh

### Eólica

In [23]:
maior_wind = eolica['Producao'].max()
print(f"Maior valor de Produção Solar registrada: {maior_wind:.3f} MWh")

Maior valor de Produção Solar registrada: 22929.000 MWh

### 70% do valor máximo Solar

In [24]:
solar_70 = maior_sol * .70
print(f"70% do máximo de produção solar equivale a: {solar_70:.3f} MWh")

70% do máximo de produção solar equivale a: 11421.200 MWh

Dataframe com registros acima desse valor

In [27]:
df_solar_70 = solar[solar['Producao'] > solar_70]
df_solar_70.head()

,Data,Horario_inicial,Horario_final,Fonte,Day_of_Year,Dia_nome,Mes_nome,Estacao,Producao
77,2025-07-08 00:00:00,13,14,Solar,189,Tuesday,July,Summer,13125
178,2025-03-19 00:00:00,13,14,Solar,78,Wednesday,March,Spring,13786
183,2025-08-17 00:00:00,12,13,Solar,229,Sunday,August,Summer,11455
187,2025-07-16 00:00:00,12,13,Solar,197,Wednesday,July,Summer,16160
207,2025-03-31 00:00:00,12,13,Solar,90,Monday,March,Spring,12441

Quantidade e porcentagem de registros acima de 70%

In [28]:
print(f"A quantidade de registros acima desse valor: {df_solar_70.shape[0]}")
solar_porcent_70 = (df_solar_70.shape[0] / dados.shape[0]) * 100
print(f"Essa quantidade representa {solar_porcent_70:.2f}% de registros da Produção Solar")

A quantidade de registros acima desse valor: 45
Essa quantidade representa 0.43% de registros da Produção Solar

### 70% do valor máximo Eólica

In [ ]:
eolica_70 = maior_wind * .70
print(f"70% do máximo de produção eolica equivale a: {eolica_70:.3f} MWh")

Dataframe com registros acima desse valor

In [30]:
df_eolica_70 = eolica[eolica['Producao'] > eolica_70]
df_eolica_70.head()

,Data,Horario_inicial,Horario_final,Fonte,Day_of_Year,Dia_nome,Mes_nome,Estacao,Producao
20,2024-01-03 00:00:00,0,1,Wind,3,Wednesday,January,Winter,17272
32,2021-03-11 00:00:00,13,14,Wind,70,Thursday,March,Spring,16144
103,2025-01-29 00:00:00,0,1,Wind,29,Wednesday,January,Winter,18199
151,2024-12-08 00:00:00,6,7,Wind,343,Sunday,December,Winter,16946
192,2024-11-19 00:00:00,2,3,Wind,324,Tuesday,November,Fall,16568

Quantidade e porcentagem de registros acima de 70%

In [31]:
print(f"A quantidade de registros acima desse valor: {df_eolica_70.shape[0]}")
eolica_porcent_70 = (df_eolica_70.shape[0] / dados.shape[0]) * 100
print(f"Essa quantidade representa {eolica_porcent_70:.2f}% de registros da Produção Eólica")

A quantidade de registros acima desse valor: 245
Essa quantidade representa 2.36% de registros da Produção Eólica

### Comparar qual fonte aparece mais acima de 70%

In [ ]:
if eolica_porcent_70 > solar_porcent_70:
  print("A Energia Eólica apresenta mais registros de produção acima de 70% do seu máximo")
elif eolica_porcent_70 < solar_porcent_70:
  print("A Energia Solar apresenta mais registros de produção acima de 70% do seu máximo")
else:
  print("As duas fontes energéticas apresentam a mesma quantidade de registros de produção acima de 70% do seu máximo")

### Por que não seria adequado utilizar o mesmo valor numérico de potência como limite para as duas fontes?

Não seria adequado utilizar diretamente o mesmo valor numérico de potência como limite para as duas fontes porque a produção de energia eólica e solar pode apresentar valores máximos diferentes. Por exemplo, se a produção máxima solar for muito maior que a eólica, usar um único limite faria com que esse valor representasse uma porcentagem diferente do máximo de cada fonte.

Por isso, é mais adequado calcular o limite de 70% individualmente para cada fonte, usando o próprio valor máximo de produção. Assim, a comparação é feita de forma justa, considerando a escala de cada variável.