# Dataset 6 — Individual Household Electric Power Consumption (UCI)
**Situação**  
Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente.



---

Grupo:
| Nome | RM |
| --- | --- |
| Caio Marinho Pereira | 572873|
<br>

## Workflow Orange
Workflow realizado no Orange para mineração de dados. Não foram encontrados valores ausentes. Foi gerado uma amostra de 20% dos dados.  
![plat1.svg]()

## Import de Bibliotecas
Adiciona as bibliotecas de análise de dados que serão usadas.

In [8]:
import pandas as pd

## Carregar dados externos
Carrega a planilha com os dados, já tratados, e traduz o nome das colunas para o português.

In [9]:
dados = pd.read_csv('/content/household.csv')

In [10]:
dados = dados.rename(columns = {'Global_active_power': 'Potencia_global_ativa',
                                'Global_reactive_power': 'Potencia_global_reativa',
                                'Voltage': 'Tensao',
                                'Global_intensity': 'Corrente_global',
                                'Sub_metering_1': 'Sub_medicao_1',
                                'Sub_metering_2': 'Sub_medicao_2',
                                'Sub_metering_3': 'Sub_medicao_3'})

### Valor máximo da potência ativa

In [11]:
pot_max = dados['Potencia_global_ativa'].max()
print(f"A maior potência ativa registrada é de: {pot_max:.3f} kWh")

A maior potência ativa registrada é de: 10.536 kWh

### 75% do valor máximo

In [12]:
limite_75 = pot_max * .75
print(f"O limite de 75% da potencia ativa equivale a: {limite_75:.3f} A")

O limite de 75% da potencia ativa equivale a: 7.902 A

DataFrame com registros de consumo acima desse limite

In [13]:
df_pot_75 = dados[dados['Potencia_global_ativa'] > limite_75]
df_pot_75['Potencia_global_ativa'].head()

3132      8.540
3630      8.278
10339     8.026
11695     8.102
27983    10.290
Name: Potencia_global_ativa, dtype: float64

Quantidade e porcentagem de registros acima do limiar

In [14]:
print(f"A quantidade de registros acima do limite é de: {df_pot_75.shape[0]}")
porcent_75 = (df_pot_75.shape[0] / dados.shape[0]) * 100
print(f"Essa quantidade representa {porcent_75:.2f}% de registros da Potencia Ativa")

A quantidade de registros acima do limite é de: 58
Essa quantidade representa 0.03% de registros da Potencia Ativa

### Corrente média da amostra

In [16]:
corrente_media = dados['Corrente_global'].mean()
print(f"Média da corrente: {corrente_media:.4f} A")

Média da corrente: 4.6344 A

### Dataframe que apresenta, simultaneamente, Potência Ativa acima de 75% do máximo e Corrente acima da média

In [20]:
df_pot_alta_corrente_alta = dados[(dados['Potencia_global_ativa'] > limite_75) & (dados['Corrente_global'] > corrente_media)]
df_pot_alta_corrente_alta.head()

,Potencia_global_ativa,Potencia_global_reativa,Tensao,Corrente_global,Sub_medicao_1,Sub_medicao_2,Sub_medicao_3
3132,8.540,0.238,236.23,36.0,80,35,17
3630,8.278,0.088,231.50,35.6,0,71,17
10339,8.026,0.066,236.45,33.8,37,73,18
11695,8.102,0.190,229.31,35.4,35,35,17
27983,10.290,0.302,230.90,44.6,35,66,17

### Efeito da inclusão da corrente

Ao considerar potência acima de 75% do máximo e corrente acima da média simultaneamente, a análise fica mais específica. A potência elevada indica alta produção, enquanto a corrente elevada mostra maior circulação de corrente no sistema. Como potência e corrente estão relacionadas pela tensão, observar as duas variáveis permite identificar períodos de produção elevada acompanhados de maior intensidade elétrica.

Assim, a inclusão da corrente funciona como um filtro adicional. Registros que possuem potência alta, mas corrente abaixo da média, são excluídos. O segundo conjunto, portanto, representa situações mais específicas de alta produção associada a alta corrente, tornando a análise mais rigorosa.