# Dataset 4 — Solar Power Generation Data (Kaggle)
**Situação**  
Uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e identificar quais inversores aparecem com maior frequência nesses momentos. Nesta atividade, o foco inicial será o arquivo de geração da planta, sem realizar junção com o arquivo de sensores.


---

Grupo:
| Nome | RM |
| --- | --- |
| Caio Marinho Pereira | 572873|
<br>

## Workflow Orange
Workflow realizado no Orange para mineração de dados. Não foram encontrados valores ausentes. Foi gerado uma amostra de 20% dos dados.  
![plat1.svg]()

## Import de Bibliotecas
Adiciona as bibliotecas de análise de dados que serão usadas.

In [2]:
import pandas as pd

## Carregar dados externos
Carrega a planilha com os dados, já tratados, e traduz o nome das colunas para o português.

In [3]:
dados = pd.read_csv('/content/plant1.csv')

In [4]:
dados = dados.rename(columns = {'DC_POWER': 'Potencia_CC',
                                'AC_POWER': 'Potencia_CA',
                                'DAILY_YIELD': 'Geracao_diaria',
                                'TOTAL_YIELD': 'Geracao_total',
                                'DATE_TIME': 'Data_hora'})

### Análise Exploratória

In [5]:
dados.head()

,SOURCE_KEY,Potencia_CC,Potencia_CA,Geracao_diaria,Geracao_total,Data_hora
0,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240510.0,2020-06-10 19:00:00
1,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206550.0,2020-05-28 00:15:00
2,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036060.0,2020-05-17 15:15:00
3,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308230.0,2020-06-01 04:15:00
4,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021700.0,2020-05-17 09:00:00

In [6]:
dados.shape

(13756, 6)

In [7]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13756 entries, 0 to 13755
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SOURCE_KEY      13756 non-null  object
 1   Potencia_CC     13756 non-null  float64
 2   Potencia_CA     13756 non-null  float64
 3   Geracao_diaria  13756 non-null  float64
 4   Geracao_total   13756 non-null  float64
 5   Data_hora       13756 non-null  object
dtypes: float64(4), object(2)
memory usage: 644.9+ KB

In [8]:
dados.describe()

        Potencia_CC   Potencia_CA  Geracao_diaria  Geracao_total
count  13756.000000  13756.000000    13756.000000   1.375600e+04
mean    3135.848662    306.695495     3319.235216   6.978829e+06
std     4023.069619    393.124284     3142.249927   4.162164e+05
min        0.000000      0.000000        0.000000   6.183640e+06
25%        0.000000      0.000000        0.000000   6.509780e+06
50%      370.071500     35.771400     2730.425000   7.146220e+06
75%     6350.562500    622.065500     6293.782500   7.268000e+06
max    14416.100000   1405.590000     9163.000000   7.846820e+06

### Maior valor de Potencia_CA

In [9]:
maior_ca = dados['Potencia_CA'].max()

print(f"Maior valor de Potência CA registrada: {maior_ca:.3f} W")

Maior valor de Potência CA registrada: 1405.590 W

### 70% do valor máximo
Define um limite superior para Potência CA, com base nos 30% valores mais altos

In [10]:
limite_70 = maior_ca * .70
print(f"O limite de 70% do consumo máximo da zona 1 equivale a: {limite_70:.3f} kWh")

O limite de 70% do consumo máximo da zona 1 equivale a: 983.913 kWh

DataFrame com registros de consumo acima desse limite

In [11]:
df_consumo_70 = dados[dados['Potencia_CA'] > limite_70]
df_consumo_70['Potencia_CA'].head()

11    1153.83
46    1032.07
48    1079.86
72    1082.44
76    1234.69
Name: Potencia_CA, dtype: float64

Quantidade e porcentagem de registros acima do limiar

In [12]:
print(f"A quantidade de registros acima do limite é de: {df_consumo_70.shape[0]}")
porcent_70 = (df_consumo_70.shape[0] / dados.shape[0]) * 100
print(f"Essa quantidade representa {porcent_70:.2f}% de registros da Potencia CA")

A quantidade de registros acima do limite é de: 1185
Essa quantidade representa 8.61% de registros da Potencia CA

### SOURCE_KEY nesse DataFrame

In [13]:
contagem = df_consumo_70['SOURCE_KEY'].value_counts()
contagem

SOURCE_KEY
adLQvlD726eNBSB    68
McdE0feGgRqW7Ca    65
ZnxXDlPa8U1GXgE    63
pkci93gMrogZuBj    62
ZoEaEvLYb1n2sOq    61
1IF53ai7Xc0U56Y    59
YxYtjZvoooNbGkE    58
sjndEbLyjtCKgGv    57
z9Y9gH1T5YWrNuG    56
uHbuxQJl8lW7ozc    55
zVJPv84UY57bAof    54
zBIq5rxdHJRwDNY    53
ih0vzX44oOqAx2f    53
WRmjgnKYAwPKWDb    52
3PZuoBAID5Wc2HD    51
iCRJl6heRkivqQ3    51
VHMLBKoKgIrUVDU    51
wCURE6d3bPkepu2    49
rGa61gmuvPhdLxV    43
7JYdWkrLSPkdwr4    43
1BY6WEcLGh8j5v7    42
bvBOhCH3iADSZry    39
Name: count, dtype: int64

### Inversor que aparece com maior frequência nos registros

O inversor adLQvlD726eNBSB foi o que apareceu com maior frequência nos registros de alta geração, com 68 ocorrências. Isso indica que ele possui a maior quantidade de registros dentro do recorte analisado. Entretanto, essa frequência, isoladamente, não permite concluir que o inversor apresenta melhor desempenho, maior disponibilidade ou menor ocorrência de falhas. Seria necessário analisar outros dados e um período mais amplo para realizar esse tipo de avaliação.